-- CTET Syllabus Tracker — full reseed, generated from CTET-February 2026 Information Bulletin (Appendix I)
-- Run this once in Supabase Dashboard -> SQL Editor -> New query, on your CTET project.
--
-- Exam-tag scheme (matches lib/features/syllabus/presentation/syllabus_navigation.dart's
-- resolveSyllabusTopicTags, which decomposes an admin-named leaf folder like
-- "Science(Hin Eng)" into the tags below rather than needing every one of the
-- ~36 language-pair leaves to duplicate this content under its own exact name):
--   'CTET'                    -> Child Development and Pedagogy (shared by every leaf)
--   'CTET Paper 1'            -> Mathematics + Environmental Studies (P-1(...) leaves)
--   'CTET Paper 2 Science'    -> Mathematics and Science (Science(...) leaves)
--   'CTET Paper 2 SST'        -> Social Studies/Social Sciences (SST(...) leaves)
--   'Language I (<Lang>)' / 'Language II (<Lang>)' -> per the leaf's chosen language pair
-- syllabus_marks_distribution stays keyed by the leaf's parent folder name
-- ('CTET Paper 1' / 'CTET Paper 2'), since that's a real folder in the catalog.

begin;

-- 1) Wipe existing syllabus content
delete from public.syllabus_progress;  -- FK references syllabus_topics.id, must go first
delete from public.syllabus_topics;
delete from public.syllabus_marks_distribution;

-- 2) Syllabus topics
insert into public.syllabus_topics (exam, subject, unit, topic_name, "order") values
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Concept of development and its relationship with learning', 1),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Principles of the development of children', 2),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Influence of Heredity & Environment', 3),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Socialization processes: Social world & children (Teacher, Parents, Peers)', 4),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Piaget, Kohlberg and Vygotsky: constructs and critical perspectives', 5),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Concepts of child-centered and progressive education', 6),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Critical perspective of the construct of Intelligence', 7),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Multi-Dimensional Intelligence', 8),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Language & Thought', 9),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Gender as a social construct; gender roles, gender-bias and educational practice', 10),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Individual differences among learners, understanding differences based on diversity of language, caste, gender, community, religion etc.', 11),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Distinction between Assessment for learning and assessment of learning; School-Based Assessment, Continuous & Comprehensive Evaluation: perspective and practice', 12),
  ('CTET', 'Child Development and Pedagogy', 'a) Child Development (Primary/Elementary School Child)', 'Formulating appropriate questions for assessing readiness levels of learners; for enhancing learning and critical thinking in the classroom and for assessing learner achievement', 13),
  ('CTET', 'Child Development and Pedagogy', 'b) Concept of Inclusive Education and Understanding Children with Special Needs', 'Addressing learners from diverse backgrounds including disadvantaged and deprived', 1),
  ('CTET', 'Child Development and Pedagogy', 'b) Concept of Inclusive Education and Understanding Children with Special Needs', 'Addressing the needs of children with learning difficulties, "impairment" etc.', 2),
  ('CTET', 'Child Development and Pedagogy', 'b) Concept of Inclusive Education and Understanding Children with Special Needs', 'Addressing the Talented, Creative, Specially abled Learners', 3),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'How children think and learn; how and why children "fail" to achieve success in school performance', 1),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'Basic processes of teaching and learning; children''s strategies of learning; learning as a social activity; social context of learning', 2),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'Child as a problem solver and a "scientific investigator"', 3),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'Alternative conceptions of learning in children, understanding children''s "errors" as significant steps in the learning process', 4),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'Cognition & Emotions', 5),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'Motivation and learning', 6),
  ('CTET', 'Child Development and Pedagogy', 'c) Learning and Pedagogy', 'Factors contributing to learning - personal & environmental', 7),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Geometry', 1),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Shapes & Spatial Understanding', 2),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Solids around Us', 3),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Numbers', 4),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Addition and Subtraction', 5),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Multiplication', 6),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Division', 7),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Measurement', 8),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Weight', 9),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Time', 10),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Volume', 11),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Data Handling', 12),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Patterns', 13),
  ('CTET Paper 1', 'Mathematics', 'a) Content', 'Money', 14),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Nature of Mathematics/Logical thinking; understanding children''s thinking and reasoning patterns and strategies of making meaning and learning', 1),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Place of Mathematics in Curriculum', 2),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Language of Mathematics', 3),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Community Mathematics', 4),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Evaluation through formal and informal methods', 5),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Problems of Teaching', 6),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Error analysis and related aspects of learning and teaching', 7),
  ('CTET Paper 1', 'Mathematics', 'b) Pedagogical Issues', 'Diagnostic and Remedial Teaching', 8),
  ('CTET Paper 1', 'Environmental Studies', 'a) Content', 'Family and Friends: Relationships, Work and Play, Animals, Plants', 1),
  ('CTET Paper 1', 'Environmental Studies', 'a) Content', 'Food', 2),
  ('CTET Paper 1', 'Environmental Studies', 'a) Content', 'Shelter', 3),
  ('CTET Paper 1', 'Environmental Studies', 'a) Content', 'Water', 4),
  ('CTET Paper 1', 'Environmental Studies', 'a) Content', 'Travel', 5),
  ('CTET Paper 1', 'Environmental Studies', 'a) Content', 'Things We Make and Do', 6),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Concept and scope of EVS', 1),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Significance of EVS, integrated EVS', 2),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Environmental Studies & Environmental Education', 3),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Learning Principles', 4),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Scope & relation to Science & Social Science', 5),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Approaches of presenting concepts', 6),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Activities', 7),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Experimentation/Practical Work', 8),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Discussion', 9),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'CCE', 10),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Teaching material/Aids', 11),
  ('CTET Paper 1', 'Environmental Studies', 'b) Pedagogical Issues', 'Problems', 12),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Knowing our Numbers', 1),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Playing with Numbers', 2),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Whole Numbers', 3),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Negative Numbers and Integers', 4),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Fractions', 5),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Introduction to Algebra', 6),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Ratio and Proportion', 7),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Basic geometrical ideas (2-D)', 8),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Understanding Elementary Shapes (2-D and 3-D)', 9),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Symmetry (reflection)', 10),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Construction (using Straight edge Scale, protractor, compasses)', 11),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Mensuration', 12),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Content', 'Data handling', 13),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Nature of Mathematics/Logical thinking', 1),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Place of Mathematics in Curriculum', 2),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Language of Mathematics', 3),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Community Mathematics', 4),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Evaluation', 5),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Remedial Teaching', 6),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Mathematics: Pedagogical Issues', 'Problem of Teaching', 7),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Sources of food', 1),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Components of food', 2),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Cleaning food', 3),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Materials of daily use', 4),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'The World of the Living', 5),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Moving Things, People and Ideas', 6),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Electric current and circuits', 7),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Magnets', 8),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Natural Phenomena', 9),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Content', 'Natural Resources', 10),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Nature & Structure of Sciences', 1),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Natural Science/Aims & objectives', 2),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Understanding & Appreciating Science', 3),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Approaches/Integrated Approach', 4),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Observation/Experiment/Discovery (Method of Science)', 5),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Innovation', 6),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Text Material/Aids', 7),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Evaluation - cognitive/psycho-motor/affective', 8),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Problems', 9),
  ('CTET Paper 2 Science', 'Mathematics and Science', 'Science: Pedagogical Issues', 'Remedial Teaching', 10),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'When, Where and How', 1),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The Earliest Societies', 2),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The First Farmers and Herders', 3),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The First Cities', 4),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Early States', 5),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'New Ideas', 6),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The First Empire', 7),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Contacts with Distant Lands', 8),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Political Developments', 9),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Culture and Science', 10),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'New Kings and Kingdoms', 11),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Sultans of Delhi', 12),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Architecture', 13),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Creation of an Empire', 14),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Social Change', 15),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Regional Cultures', 16),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The Establishment of Company Power', 17),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Rural Life and Society', 18),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Colonialism and Tribal Societies', 19),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The Revolt of 1857-58', 20),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Women and Reform', 21),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'Challenging the Caste System', 22),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'The Nationalist Movement', 23),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'History', 'India After Independence', 24),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Geography as a social study and as a science', 1),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Planet: Earth in the solar system', 2),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Globe', 3),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Environment in its totality: natural and human environment', 4),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Air', 5),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Water', 6),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Human Environment: settlement, transport and communication', 7),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Resources: Types - Natural and Human', 8),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Geography', 'Agriculture', 9),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Diversity', 1),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Government', 2),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Local Government', 3),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Making a Living', 4),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Democracy', 5),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'State Government', 6),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Understanding Media', 7),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Unpacking Gender', 8),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'The Constitution', 9),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Parliamentary Government', 10),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'The Judiciary', 11),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Social and Political Life', 'Social Justice and the Marginalised', 12),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Concept & Nature of Social Science/Social Studies', 1),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Class Room Processes, activities and discourse', 2),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Developing Critical thinking', 3),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Enquiry/Empirical Evidence', 4),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Problems of teaching Social Science/Social Studies', 5),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Sources - Primary & Secondary', 6),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Projects Work', 7),
  ('CTET Paper 2 SST', 'Social Studies/Social Sciences', 'Pedagogical Issues', 'Evaluation', 8),
  ('Language I (English)', 'Language I (English)', 'a) Language Comprehension', 'Reading unseen passages - two passages, one prose or drama and one poem, with questions on comprehension, inference, grammar and verbal ability (prose passage may be literary, scientific, narrative or discursive)', 1),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Learning and acquisition', 1),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Principles of language teaching', 2),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Role of listening and speaking; function of language and how children use it as a tool', 3),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Critical perspective on the role of grammar in learning a language for communicating ideas verbally and in written form', 4),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Challenges of teaching language in a diverse classroom; language difficulties, errors and disorders', 5),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Language skills', 6),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Evaluating language comprehension and proficiency: speaking, listening, reading and writing', 7),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Teaching-learning materials: textbook, multi-media materials, multilingual resource of the classroom', 8),
  ('Language I (English)', 'Language I (English)', 'b) Pedagogy of Language Development', 'Remedial teaching', 9),
  ('Language II (English)', 'Language II (English)', 'a) Comprehension', 'Two unseen prose passages (discursive or literary or narrative or scientific) with questions on comprehension, grammar and verbal ability', 1),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Learning and acquisition', 1),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Principles of language teaching', 2),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Role of listening and speaking; function of language and how children use it as a tool', 3),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Critical perspective on the role of grammar in learning a language for communicating ideas verbally and in written form', 4),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Challenges of teaching language in a diverse classroom; language difficulties, errors and disorders', 5),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Language skills', 6),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Evaluating language comprehension and proficiency: speaking, listening, reading and writing', 7),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Teaching-learning materials: textbook, multi-media materials, multilingual resource of the classroom', 8),
  ('Language II (English)', 'Language II (English)', 'b) Pedagogy of Language Development', 'Remedial teaching', 9),
  ('Language I (Hindi)', 'Language I (Hindi)', 'क) भाषा बोधगम्यता', 'अपठित गद्यांशों का वाचन - दो गद्यांश, एक गद्य या नाटक तथा एक कविता, जिन पर बोधगम्यता, अनुमान, व्याकरण और शाब्दिक क्षमता से संबंधित प्रश्न होंगे (गद्यांश साहित्यिक, वैज्ञानिक, वर्णनात्मक या विचारात्मक हो सकता है)', 1),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'अधिगम और अर्जन (भाषा सीखना व स्वाभाविक रूप से ग्रहण करना)', 1),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'भाषा शिक्षण के सिद्धांत', 2),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'सुनने और बोलने की भूमिका; भाषा का कार्य और बच्चे इसे एक उपकरण के रूप में कैसे उपयोग करते हैं', 3),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'विचारों को मौखिक और लिखित रूप में संप्रेषित करने हेतु भाषा सीखने में व्याकरण की भूमिका पर आलोचनात्मक दृष्टिकोण', 4),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'विविधतापूर्ण कक्षा में भाषा शिक्षण की चुनौतियाँ; भाषा संबंधी कठिनाइयाँ, त्रुटियाँ और विकार', 5),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'भाषा कौशल', 6),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'भाषा बोध और दक्षता का मूल्यांकन: बोलना, सुनना, पढ़ना और लिखना', 7),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'शिक्षण-अधिगम सामग्री: पाठ्यपुस्तक, बहु-मीडिया सामग्री, कक्षा के बहुभाषी संसाधन', 8),
  ('Language I (Hindi)', 'Language I (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'उपचारात्मक शिक्षण', 9),
  ('Language II (Hindi)', 'Language II (Hindi)', 'क) बोधगम्यता', 'दो अपठित गद्यांश (विचारात्मक, साहित्यिक, वर्णनात्मक या वैज्ञानिक) जिन पर बोधगम्यता, व्याकरण और शाब्दिक क्षमता से संबंधित प्रश्न होंगे', 1),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'अधिगम और अर्जन (भाषा सीखना व स्वाभाविक रूप से ग्रहण करना)', 1),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'भाषा शिक्षण के सिद्धांत', 2),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'सुनने और बोलने की भूमिका; भाषा का कार्य और बच्चे इसे एक उपकरण के रूप में कैसे उपयोग करते हैं', 3),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'विचारों को मौखिक और लिखित रूप में संप्रेषित करने हेतु भाषा सीखने में व्याकरण की भूमिका पर आलोचनात्मक दृष्टिकोण', 4),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'विविधतापूर्ण कक्षा में भाषा शिक्षण की चुनौतियाँ; भाषा संबंधी कठिनाइयाँ, त्रुटियाँ और विकार', 5),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'भाषा कौशल', 6),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'भाषा बोध और दक्षता का मूल्यांकन: बोलना, सुनना, पढ़ना और लिखना', 7),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'शिक्षण-अधिगम सामग्री: पाठ्यपुस्तक, बहु-मीडिया सामग्री, कक्षा के बहुभाषी संसाधन', 8),
  ('Language II (Hindi)', 'Language II (Hindi)', 'ख) भाषा विकास शिक्षाशास्त्र', 'उपचारात्मक शिक्षण', 9),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'क) भाषाबोधगम्यता', 'अपठितगद्यांशवाचनम् - द्वौ गद्यांशौ, एकः गद्यः वा नाट्यांशः, अपरः पद्यांशः, यत्र बोधगम्यता-अनुमान-व्याकरण-शाब्दिकक्षमता-विषयकाः प्रश्नाः भविष्यन्ति (गद्यांशः साहित्यिकः, वैज्ञानिकः, वर्णनात्मकः वा विचारात्मकः भवितुम् अर्हति)', 1),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'अधिगमः च अर्जनं च', 1),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'भाषाशिक्षणस्य सिद्धान्ताः', 2),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'श्रवण-भाषणयोः भूमिका; भाषायाः कार्यं तथा बालकाः तां साधनरूपेण कथं उपयुञ्जते', 3),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'मौखिक-लिखितरूपेण विचारसंप्रेषणार्थं भाषाध्ययने व्याकरणस्य भूमिकाविषये समीक्षात्मकं दृष्टिकोणम्', 4),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'विविधतायुक्तकक्षायां भाषाशिक्षणस्य आव्हानानि; भाषासम्बद्धकठिनताः, त्रुटयः दोषाश्च', 5),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'भाषाकौशलानि', 6),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'भाषाबोधस्य दक्षतायाश्च मूल्यांकनम्: भाषणं, श्रवणं, पठनं लेखनं च', 7),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'शिक्षण-अधिगमसामग्री: पाठ्यपुस्तकम्, बहुमाध्यमसामग्री, कक्षायाः बहुभाषिकसाधनानि', 8),
  ('Language I (Sanskrit)', 'Language I (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'उपचारात्मकशिक्षणम्', 9),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'क) बोधगम्यता', 'द्वौ अपठितगद्यांशौ (विचारात्मकौ, साहित्यिकौ, वर्णनात्मकौ वा वैज्ञानिकौ) यत्र बोधगम्यता-व्याकरण-शाब्दिकक्षमता-विषयकाः प्रश्नाः भविष्यन्ति', 1),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'अधिगमः च अर्जनं च', 1),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'भाषाशिक्षणस्य सिद्धान्ताः', 2),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'श्रवण-भाषणयोः भूमिका; भाषायाः कार्यं तथा बालकाः तां साधनरूपेण कथं उपयुञ्जते', 3),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'मौखिक-लिखितरूपेण विचारसंप्रेषणार्थं भाषाध्ययने व्याकरणस्य भूमिकाविषये समीक्षात्मकं दृष्टिकोणम्', 4),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'विविधतायुक्तकक्षायां भाषाशिक्षणस्य आव्हानानि; भाषासम्बद्धकठिनताः, त्रुटयः दोषाश्च', 5),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'भाषाकौशलानि', 6),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'भाषाबोधस्य दक्षतायाश्च मूल्यांकनम्: भाषणं, श्रवणं, पठनं लेखनं च', 7),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'शिक्षण-अधिगमसामग्री: पाठ्यपुस्तकम्, बहुमाध्यमसामग्री, कक्षायाः बहुभाषिकसाधनानि', 8),
  ('Language II (Sanskrit)', 'Language II (Sanskrit)', 'ख) भाषाविकासशिक्षाशास्त्रम्', 'उपचारात्मकशिक्षणम्', 9),
  ('Language I (Urdu)', 'Language I (Urdu)', 'الف) فہمِ زبان', 'غیر مانوس اقتباسات کا مطالعہ - دو اقتباسات، ایک نثر یا ڈرامہ اور ایک نظم، جن پر فہمِ عبارت، استخراج، گرامر اور زبانی صلاحیت سے متعلق سوالات ہوں گے (نثری اقتباس ادبی، سائنسی، بیانیہ یا استدلالی ہو سکتا ہے)', 1),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'سیکھنے کا عمل اور زبان کا حصول', 1),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'زبان کی تدریس کے اصول', 2),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'سننے اور بولنے کا کردار؛ زبان کا فعل اور بچے اسے ایک آلے کے طور پر کیسے استعمال کرتے ہیں', 3),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'خیالات کو زبانی اور تحریری طور پر پہنچانے کے لیے زبان سیکھنے میں گرامر کے کردار پر تنقیدی نقطہ نظر', 4),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'متنوع کلاس روم میں زبان کی تدریس کے چیلنجز؛ زبان سے متعلق مشکلات، غلطیاں اور خرابیاں', 5),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'زبان کی مہارتیں', 6),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'زبان کی فہم اور مہارت کا جائزہ: بولنا، سننا، پڑھنا اور لکھنا', 7),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'تدریسی و تعلیمی مواد: نصابی کتاب، ملٹی میڈیا مواد، کلاس روم کے کثیر لسانی وسائل', 8),
  ('Language I (Urdu)', 'Language I (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'اصلاحی تدریس', 9),
  ('Language II (Urdu)', 'Language II (Urdu)', 'الف) فہمِ عبارت', 'دو غیر مانوس نثری اقتباسات (استدلالی، ادبی، بیانیہ یا سائنسی) جن پر فہمِ عبارت، گرامر اور زبانی صلاحیت سے متعلق سوالات ہوں گے', 1),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'سیکھنے کا عمل اور زبان کا حصول', 1),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'زبان کی تدریس کے اصول', 2),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'سننے اور بولنے کا کردار؛ زبان کا فعل اور بچے اسے ایک آلے کے طور پر کیسے استعمال کرتے ہیں', 3),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'خیالات کو زبانی اور تحریری طور پر پہنچانے کے لیے زبان سیکھنے میں گرامر کے کردار پر تنقیدی نقطہ نظر', 4),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'متنوع کلاس روم میں زبان کی تدریس کے چیلنجز؛ زبان سے متعلق مشکلات، غلطیاں اور خرابیاں', 5),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'زبان کی مہارتیں', 6),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'زبان کی فہم اور مہارت کا جائزہ: بولنا، سننا، پڑھنا اور لکھنا', 7),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'تدریسی و تعلیمی مواد: نصابی کتاب، ملٹی میڈیا مواد، کلاس روم کے کثیر لسانی وسائل', 8),
  ('Language II (Urdu)', 'Language II (Urdu)', 'ب) ترقیِ زبان کا فن تدریس', 'اصلاحی تدریس', 9);

-- 3) Marks distribution (Appendix I, Structure and Content)
insert into public.syllabus_marks_distribution (exam, table_data) values
('CTET Paper 1', '[
  ["Subject", "MCQs", "Marks"],
  ["Child Development and Pedagogy", "30", "30"],
  ["Mathematics", "30", "30"],
  ["Environmental Studies", "30", "30"],
  ["Language I", "30", "30"],
  ["Language II", "30", "30"],
  ["Total", "150", "150"]
]'::jsonb),
('CTET Paper 2', '[
  ["Subject", "MCQs", "Marks"],
  ["Child Development and Pedagogy", "30", "30"],
  ["Mathematics and Science (for Maths/Science teacher) OR Social Studies/Social Science (for SSt teacher)", "60", "60"],
  ["Language I", "30", "30"],
  ["Language II", "30", "30"],
  ["Total", "150", "150"]
]'::jsonb)
on conflict (exam) do update set table_data = excluded.table_data;

commit;
