// PLACEHOLDER — this file is normally auto-generated by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
// from the `mobile_app/` directory, logged into the Firebase account that
// owns the project created for this app (see mobile_app/README.md, step 1).
// That command overwrites this exact file with your real project's keys.
// Do not commit real API keys over this placeholder without understanding
// that they are safe to be public for Firebase web/mobile apps (access is
// controlled by Firebase Auth + Security Rules, not by keeping this file
// secret) — but the values below are dummy placeholders and will not work
// until replaced.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform — run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.firebasestorage.app',
    iosBundleId: 'com.adnankhanaligyt.ctetTetPrep',
  );

  // Web wasn't part of the original plan (Android first), but is kept
  // buildable so the app can still be previewed in a browser (e.g. for a
  // design review) before a real Firebase project exists. `flutterfire
  // configure` will overwrite this with real values if web is ever
  // actually shipped.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.firebasestorage.app',
    authDomain: 'REPLACE_ME.firebaseapp.com',
  );
}
